on:
  - push

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          chmod +x ./gradlew
          ./gradlew test

  lint:
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          chmod +x ./gradlew
          ./gradlew detekt

      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: build/reports/detekt/merged.sarif
