on:
  - push

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          chmod +x ./gradlew
          ./gradlew test

  instrument-test:
    runs-on: macos-12
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    strategy:
      matrix:
        api-level: [28, 29, 30, 31, 32, 33]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          script: |
            chmod +x ./gradlew
            ./gradlew connectedAndroidTest

  lint:
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          chmod +x ./gradlew
          ./gradlew detekt

      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: build/reports/detekt/merged.sarif
