on:
  - push

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  instrument-test:
    runs-on: macos-12
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    strategy:
      matrix:
        api-level: [28, 29, 30, 31, 32, 33]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: gradle/gradle-build-action@v2

      - uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - uses: reactivecircus/android-emulator-runner@v2
        if: steps.avd-cache.outputs.cache-hit != 'true'
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest connectedAndroidTestCollectReports

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: instrument-test-result-${{ matrix.api-level }}
          path: build/outputs/androidTest

  lint:
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: build/reports/detekt/merged.sarif
